GET http://localhost:5555

###
GET http://localhost:5555/admin

####### ESTADOS ---------------------------------------------------------------

### Criar estado
POST http://localhost:5555/estados
Content-Type: application/json

{
    "id": 5,
    "nome": "Tocantins",
    "sigla": "TO"
}

### Buscar os estados
GET http://localhost:5555/estados

### Atualizar estado
PUT http://localhost:5555/estados/1
Content-Type: application/json

{
  "nome": "Rio de Janeiro",
  "sigla": "RJ"
}

### Deletar estado
DELETE http://localhost:5555/estados
Content-Type: application/json

{
    "id": 2
}

######## CIDADES ---------------------------------------------------------------

### Criar cidade
POST http://localhost:5555/cidades
Content-Type: application/json

{
    "nome": "Barretos",
    "estado_id": 1
}

### Buscar as cidades
GET http://localhost:5555/cidades

### Atualizar cidade
PUT http://localhost:5555/cidades/1
Content-Type: application/json

{
  "nome": "Jundiaí",
  "estado_id": 1
}

### Deletar cidade 1
DELETE http://localhost:5555/cidades/1
Content-Type: application/json


####### PRODUTOS ---------------------------------------------------------------

### Criar produto

POST http://localhost:5555/produtos
Content-Type: application/json

{
  "descricao": "Cafe",
  "valor_unitario": 2.0
}

### Buscar os produtos
GET http://localhost:5555/produtos

### Atualizar produto
PUT http://localhost:5555/produtos/1
Content-Type: application/json

{
  "descricao": "Café",
  "valor_unitario": 8.0
}

### Deletar produto
DELETE http://localhost:5555/produtos/1

######  ENDERECO ---------------------------------------------------------------

### Criar endereco
POST http://localhost:5555/endereco
Content-Type: application/json

{
  "usuario_id": 1,
  "rua": "Rua 3",
  "numero": "4",
  "bairro": "Bairro Cinco",
  "cidade_id": 1,
  "telefone": "(12) 3456-7890"
}

### Buscar os enderecos
GET http://localhost:5555/endereco

### Atualizar endereco 
PUT http://localhost:5555/endereco/1
Content-Type: application/json

{
  "usuario_id": 1,
  "rua": "Rua Dois",
  "numero": "3",
  "bairro": "Bairro Quatro",
  "cidade_id": 1,
  "telefone": "(98) 7654-3210"
}

### Deletar endereco
DELETE http://localhost:5555/endereco/1

###### COMPRAS ---------------------------------------------------------------

### Criar compras
POST http://localhost:5555/compras
Content-Type: application/json

{
  "usuario_id": 1,
  "endereco_id": 1,
  "data": "2023-08-10T12:00:10"
}

### Buscar as compras
GET http://localhost:5555/compras

### Atualizar compra
PUT http://localhost:5555/compras/1
Content-Type: application/json

{
  "usuario_id": 2,
  "endereco_id": 2,
  "data": "2023-08-15T14:00:59"
}

### Deletar compra
DELETE http://localhost:5555/compras/1
